on: ["push", "pull_request"]

name: Test Coveralls

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests and calculate coverage
        run: make test-coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
